[Variables]
thinFont=Gibson Light
thickFont=Gibson

[styleTitle]
StringCase=NONE
FontFace=#thickFont#
FontSize=12
FontColor=64,61,52, 255
AntiAlias=1
ClipString=1
DynamicVariables=1

[styleLeftText]
StringAlign=LEFT
StringCase=NONE
FontFace=#thickFont#
FontSize=12
FontColor=64,61,52, 255
AntiAlias=1
ClipString=1
DynamicVariables=1

[styleRightText]
StringAlign=RIGHT
StringCase=NONE
FontFace=#thickFont#
FontSize=12
FontColor=64,61,52, 255
AntiAlias=1
ClipString=1
DynamicVariables=1

[styleBar]
BarColor=64,61,52, 255
BarOrientation=HORIZONTAL
SolidColor=82,93,94,75
W=250
H=3
