[Variables]
Player=AIMP
; Change this variable to your media player.
; Visit this page for all supported players: http://docs.rainmeter.net/manual/plugins/nowplaying#playerlist
alignRight=0
switchedOn=1
Size=(#WORKAREAWIDTH#*0.3);
;
0 = MUSIC, 1 = SPOTIFY, 2 = UNP
MusicSwitch=0
;
adaptiveHideActive=1
unpDirectory=%USERPROFILE%\Documents\Rainmeter\
stowAway=0
stowAwayName=NULL
bottomText=mTitle
topText=mArtist
thinFont=Gibson Light
thickFont=方正准圆简体
mediaTextPositionHor=0
mediaTextAlignment=Left
interfaceTextAlignment=Right
PlayerPath=#PlayerPath#

[Variables]
Player=WLM
http://docs.rainmeter.net/manual/plugins/nowplaying#playerlist
alignRight=0
switchedOn=1
Size=(#WORKAREAWIDTH#*0.3);
;
0 = MUSIC, 1 = SPOTIFY, 2 = UNP
MusicSwitch=0
;
adaptiveHideActive=1
unpDirectory=%USERPROFILE%\Documents\Rainmeter\
stowAway=0
stowAwayName=NULL
bottomText=mTitle
topText=mArtist
thinFont=Gibson Light
thickFont=Gibson
mediaTextPositionHor=0
mediaTextAlignment=Left
interfaceTextAlignment=Right
PlayerPath=#PlayerPath#

[Variables]
Player=WMP
http://docs.rainmeter.net/manual/plugins/nowplaying#playerlist
alignRight=0
switchedOn=1
Size=(#WORKAREAWIDTH#*0.3);
;
0 = MUSIC, 1 = SPOTIFY, 2 = UNP
MusicSwitch=0
;
adaptiveHideActive=1
unpDirectory=%USERPROFILE%\Documents\Rainmeter\
stowAway=0
stowAwayName=NULL
bottomText=mTitle
topText=mArtist
thinFont=Gibson Light
thickFont=Gibson
mediaTextPositionHor=0
mediaTextAlignment=Left
interfaceTextAlignment=Right
PlayerPath=#PlayerPath#